Add unit tests for com.ctrip.framework.apollo.core.utils.ByteUtil
Diffblue-benchmarks/apollo pull request #2
Opened 2019-06-19 09:24 UTC by JohnLBergqvist

I've analysed your codebase and noticed that `com.ctrip.framework.apollo.core.utils.ByteUtil` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

2019-06-19 10:14 UTC, petersear commented on apollo-core/src/test/java/com/ctrip/framework/apollo/core/utils/ByteUtilTest.java
> +  public void testInt3() {
Some non-zero values perhaps?

2019-06-20 09:24 UTC, paulkennethkent requested changes
~Are there any other classes for this project?~

Ignore this, I've just found your other PR.

2019-06-20 09:26 UTC, paulkennethkent approved these changes

2019-06-20 09:36 UTC, petersear approved these changes

2019-06-20 10:51 UTC, closed without merging